on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.11.x, 1.12.x, 1.13.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    env:
      GO111MODULE: on
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code to gopath
      uses: actions/checkout@v1
      with:
        path: go/src/github.com/hyperledger-labs/fabric-chaincode-wasm
    - name: Debug dirs and env
      run: |
        pwd
        echo "###### ENV #######"
        env
        echo "###### GO ENV #######"
        go env
        echo ${GOPATH}
      env:
        GOPATH: /home/runner/work/fabric-chaincode-wasm/go
    - name: Install ginkgo
      run: |
        go get -u github.com/onsi/ginkgo/ginkgo
      env:
        GOPATH: /home/runner/work/fabric-chaincode-wasm/go
    - name: Get HLF
      working-directory: ./../..
      run: |
        mkdir hyperledger
        cd hyperledger
        mkdir fabric
        cd fabric
        pwd
        git clone https://github.com/hyperledger/fabric . --branch v1.4.0 --single-branch --depth 1
    - name: Install ccenv couchdb kafka zookeeper
      working-directory: ./../../hyperledger/fabric
      run: |
        docker pull hyperledger/fabric-ccenv:amd64-1.4.0
        docker tag hyperledger/fabric-ccenv:amd64-1.4.0 hyperledger/fabric-ccenv:amd64-latest
        docker pull hyperledger/fabric-zookeeper:0.4.14
        docker tag hyperledger/fabric-zookeeper:0.4.14 hyperledger/fabric-zookeeper:latest
        docker pull hyperledger/fabric-kafka:0.4.14
        docker tag hyperledger/fabric-kafka:0.4.14 hyperledger/fabric-kafka:latest
        docker pull hyperledger/fabric-couchdb:0.4.14
        docker tag hyperledger/fabric-couchdb:0.4.14 hyperledger/fabric-couchdb:latest
      env:
        GOPATH: /home/runner/work/fabric-chaincode-wasm/go
    - name: Build & Unit Test
      run: |
        make
    - name: Integration test
      working-directory: ./integration/e2e
      run: |
        pwd
        go test
      env:
        GOPATH: /home/runner/work/fabric-chaincode-wasm/go
        GO111MODULE: off